// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/jinzhu/gorm"
	"github.com/vpaliy/telex/api/channels"
	"github.com/vpaliy/telex/api/messages"
	"github.com/vpaliy/telex/api/users"
	"github.com/vpaliy/telex/rtm"
	gorm2 "github.com/vpaliy/telex/store/gorm"
)

import (
	_ "github.com/vpaliy/telex/api"
)

// Injectors from di.go:

func InitializeDispatcher(database *gorm.DB) rtm.Dispatcher {
	userStore := gorm2.NewUserStore(database)
	messageStore := gorm2.NewMessageStore(database)
	subscriptionStore := gorm2.NewSubscriptionStore(database)
	channelStore := gorm2.NewChannelStore(database)
	repository := rtm.NewRepository(userStore, messageStore, subscriptionStore, channelStore)
	dispatcher := rtm.NewDispatcher(repository)
	return dispatcher
}

func InitializeChannelHandler(database *gorm.DB) *channels.Handler {
	channelStore := gorm2.NewChannelStore(database)
	subscriptionStore := gorm2.NewSubscriptionStore(database)
	userStore := gorm2.NewUserStore(database)
	handler := channels.NewHandler(channelStore, subscriptionStore, userStore)
	return handler
}

func InitializeUserHandler(database *gorm.DB) *users.Handler {
	userStore := gorm2.NewUserStore(database)
	handler := users.NewHandler(userStore)
	return handler
}

func InitializeMessageHandler(database *gorm.DB) *messages.Handler {
	channelStore := gorm2.NewChannelStore(database)
	messageStore := gorm2.NewMessageStore(database)
	handler := messages.NewHandler(channelStore, messageStore)
	return handler
}

// di.go:

var StoreSet = wire.NewSet(gorm2.NewSubscriptionStore, gorm2.NewChannelStore, gorm2.NewUserStore, gorm2.NewMessageStore)
