// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/jinzhu/gorm"
	"github.com/vpaliy/telex/channels"
	"github.com/vpaliy/telex/messages"
	"github.com/vpaliy/telex/rtm"
	gorm2 "github.com/vpaliy/telex/store/gorm"
	"github.com/vpaliy/telex/users"
)

import (
	_ "github.com/vpaliy/telex/handler"
)

// Injectors from di.go:

func InitializeChannelHandler(database *gorm.DB) *channels.Handler {
	channelStore := gorm2.NewChannelStore(database)
	subscriptionStore := gorm2.NewSubscriptionStore(database)
	userStore := gorm2.NewUserStore(database)
	handler := channels.NewHandler(channelStore, subscriptionStore, userStore)
	return handler
}

func InitializeUserHandler(database *gorm.DB) *users.Handler {
	userStore := gorm2.NewUserStore(database)
	handler := users.NewHandler(userStore)
	return handler
}

func InitializeMessageHandler(database *gorm.DB) *messages.Handler {
	channelStore := gorm2.NewChannelStore(database)
	messageStore := gorm2.NewMessageStore(database)
	handler := messages.NewHandler(channelStore, messageStore)
	return handler
}

// di.go:

func NewRepository() *rtm.TestRepository {
	return &rtm.TestRepository{}
}

func InitializeChannelManager() rtm.ChannelManager {

	return rtm.NewChannelManager(NewRepository())
}
